#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
collector="$repository_root/scripts/collect-manifests.sh"
temporary_directory="$(mktemp -d)"
trap 'rm -rf "$temporary_directory"' EXIT
fixture="$temporary_directory/source"
mkdir -p "$fixture/crates/sample/src" "$fixture/crates/mesh-llm-ui" \
  "$fixture/website" "$fixture/.cargo" "$temporary_directory/bundles"

expect_failure() {
  if "$@" >"$temporary_directory/failure.log" 2>&1; then
    echo "expected command to fail: $*" >&2
    exit 1
  fi
}

collect() {
  "$BASH" "$collector" --source "$fixture" \
    --output "$temporary_directory/bundles/$1" --profile "${2:-public}"
}

commit_fixture() {
  git -C "$fixture" add .
  git -C "$fixture" -c user.name='Collector fixture' \
    -c user.email=collector@example.invalid -c commit.gpgsign=false \
    -c core.hooksPath=/dev/null commit -qm "$1"
}

hash_file() {
  if command -v sha256sum >/dev/null; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

assert_payload() {
  local directory="$temporary_directory/bundles/$1/dependencies"
  local path expected
  jq -e '.schema == 1 and (keys == ["files", "schema"])
    and (.files | length > 0)
    and all(.files[]; keys == ["path", "sha256"])
    and ([.files[].path] == ([.files[].path] | sort | unique))' \
    "$directory/dependency-index.json" >/dev/null
  while IFS=$'\t' read -r path expected; do
    [[ "$(hash_file "$directory/$path")" == "$expected" ]]
  done < <(jq -r '.files[] | [.path, .sha256] | @tsv' \
    "$directory/dependency-index.json")
  (cd "$directory" && find . -type f ! -name dependency-index.json \
    | sed 's|^./||' | LC_ALL=C sort) > "$temporary_directory/actual-files"
  jq -r '.files[].path' "$directory/dependency-index.json" \
    > "$temporary_directory/index-files"
  cmp "$temporary_directory/actual-files" "$temporary_directory/index-files"
}

assert_payload_changed() {
  local before="$temporary_directory/bundles/$1/dependencies/dependency-index.json"
  local after="$temporary_directory/bundles/$2/dependencies/dependency-index.json"
  if cmp -s "$before" "$after"; then
    echo "dependency change did not change the payload index: $1 -> $2" >&2
    exit 1
  fi
  assert_payload "$2"
}

cat > "$fixture/Cargo.toml" <<'EOF'
[workspace]
members = ["crates/sample"]
resolver = "2"
EOF
cat > "$fixture/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "collector-sample"
version = "0.1.0"
EOF
cat > "$fixture/crates/sample/Cargo.toml" <<'EOF'
[package]
name = "collector-sample"
version = "0.1.0"
edition = "2021"
EOF
printf 'pub fn original() {}\n' > "$fixture/crates/sample/src/lib.rs"
printf '{"name":"ui","private":true}\n' > "$fixture/crates/mesh-llm-ui/package.json"
printf 'engine-strict=true\n' > "$fixture/crates/mesh-llm-ui/.npmrc"
printf 'registry=https://registry.npmjs.org/\n' > "$fixture/.npmrc"
printf '[net]\noffline = true\n' > "$fixture/.cargo/config.toml"
printf "lockfileVersion: '9.0'\n" > "$fixture/crates/mesh-llm-ui/pnpm-lock.yaml"
printf 'packages:\n  - "."\n' > "$fixture/crates/mesh-llm-ui/pnpm-workspace.yaml"
printf '{"name":"website","lockfileVersion":3,"packages":{}}\n' \
  > "$fixture/website/package-lock.json"
printf 'Initial source documentation\n' > "$fixture/README.md"
git -C "$fixture" init -q
commit_fixture baseline
collect baseline
collect repeat
diff -qr "$temporary_directory/bundles/baseline" "$temporary_directory/bundles/repeat"
assert_payload baseline
baseline="$temporary_directory/bundles/baseline"
[[ "$(cat "$baseline/source-revision.txt")" == "$(git -C "$fixture" rev-parse HEAD)" ]]
[[ "$(cat "$baseline/profile.txt")" == public ]]
[[ ! -e "$baseline/Cargo.toml" && ! -e "$baseline/dependencies/README.md" ]]
jq -e '.profile == "public" and (.source_revision | test("^[0-9a-f]{40}$"))
  and any(.manifests[]; .path == "crates/mesh-llm-ui/.npmrc" and .ecosystem == "configuration")
  and any(.manifests[]; .path == "crates/mesh-llm-ui/pnpm-workspace.yaml" and .ecosystem == "configuration")
  and all(.manifests[]; .path != "crates/sample/src/lib.rs")' \
  "$baseline/manifest-index.json" >/dev/null
[[ "$(cat "$baseline/dependencies/crates/sample/src/lib.rs")" == '#![allow(dead_code)]' ]]

# Exercise the directory artifact boundary with the actual workflow input. Hidden
# filtering follows the pinned upload-artifact action's excludeHiddenFiles option.
# The negative roundtrip reproduces the hosted .npmrc failure; the enabled path
# must preserve every indexed checksum, including hidden-directory Cargo config.
python3 - "$repository_root" "$temporary_directory" "$BASH" <<'PYTHON'
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys
import zipfile

repository, temporary = map(Path, sys.argv[1:3])
bash = sys.argv[3]
workflow = (repository / ".github/workflows/build-and-push.yml").read_text()
upload = re.search(r"      - name: Upload manifest bundles\n(.*?)(?=\n  [a-z_]+:|\n      - name:)", workflow, re.S).group(1)
assert "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a" in upload
assert "          path: build-context/manifests\n" in upload
configured_hidden = re.search(r"^          include-hidden-files: (true|false)$", upload, re.M)
include_hidden = configured_hidden is not None and configured_hidden.group(1) == "true"
download = (repository / ".github/workflows/stage-image-family.yml").read_text()
download = re.search(r"      - name: Download manifest bundles\n(.*?)(?=\n      - name:)", download, re.S).group(1)
assert "          path: build-context/manifests\n" in download
assert "name: mesh-manifest-bundles-${{ github.run_attempt }}" in upload and "name: mesh-manifest-bundles-${{ github.run_attempt }}" in download
source = temporary / "bundles/baseline"
indexed = json.loads((source / "dependencies/dependency-index.json").read_text())["files"]
for required in (".npmrc", "crates/mesh-llm-ui/.npmrc", ".cargo/config.toml"):
    assert any(item["path"] == required for item in indexed), required
    assert (source / "dependencies" / required).is_file(), required

for name, hidden, success in (("default", False, False), ("configured", include_hidden, True)):
    archive = temporary / (name + ".zip")
    restored = temporary / ("download-" + name)
    # upload's single-directory root is omitted; profile-relative paths survive.
    with zipfile.ZipFile(archive, "w") as zipped:
        for path in sorted(source.rglob("*")):
            relative = path.relative_to(source)
            if path.is_file() and (hidden or not any(part.startswith(".") for part in relative.parts)):
                zipped.write(path, Path("public") / relative)
    with zipfile.ZipFile(archive) as zipped:
        zipped.extractall(restored)
    dependencies = restored / "public/dependencies"
    result = subprocess.run([bash, str(repository / "scripts/prepare-ui-dependencies.sh"),
                             str(dependencies), str(temporary / ("ui-" + name))], capture_output=True, text=True)
    if not success:
        assert result.returncode != 0 and ".npmrc" in result.stderr, result.stderr
        assert not (dependencies / ".cargo/config.toml").exists()
    else:
        assert result.returncode == 0, result.stderr
        for item in indexed:
            path = dependencies / item["path"]
            assert path.is_file(), item["path"]
            assert hashlib.sha256(path.read_bytes()).hexdigest() == item["sha256"], item["path"]
        assert (temporary / "ui-configured/.npmrc").read_bytes() == (source / "dependencies/.npmrc").read_bytes()
        assert (temporary / "ui-configured/crates/mesh-llm-ui/.npmrc").read_bytes() == (source / "dependencies/crates/mesh-llm-ui/.npmrc").read_bytes()
PYTHON

# A new source revision changes audit metadata, not resolution inputs or stubs.
printf 'New source documentation\n' > "$fixture/README.md"
printf 'pub fn changed_source() {}\n' > "$fixture/crates/sample/src/lib.rs"
commit_fixture source-only
collect source-only
diff -qr "$baseline/dependencies" "$temporary_directory/bundles/source-only/dependencies"
expect_failure cmp -s "$baseline/source-revision.txt" \
  "$temporary_directory/bundles/source-only/source-revision.txt"
expect_failure cmp -s "$baseline/manifest-index.json" \
  "$temporary_directory/bundles/source-only/manifest-index.json"

collect self-hosted self-hosted
diff -qr "$temporary_directory/bundles/source-only/dependencies" \
  "$temporary_directory/bundles/self-hosted/dependencies"
jq -e '.profile == "self-hosted"' \
  "$temporary_directory/bundles/self-hosted/manifest-index.json" >/dev/null

# Only tracked package-manager configuration is included.
mkdir -p "$fixture/untracked"
printf 'engine-strict=false\n' > "$fixture/untracked/.npmrc"
collect untracked
diff -qr "$baseline/dependencies" "$temporary_directory/bundles/untracked/dependencies"

printf '{"name":"website","lockfileVersion":3,"packages":{"":{"version":"2.0.0"}}}\n' \
  > "$fixture/website/package-lock.json"
collect dependency-change
assert_payload_changed source-only dependency-change

printf 'engine-strict=false\n' > "$fixture/crates/mesh-llm-ui/.npmrc"
collect npm-config-change
assert_payload_changed dependency-change npm-config-change

printf 'packages:\n  - "."\noverrides:\n  example: 1.0.0\n' \
  > "$fixture/crates/mesh-llm-ui/pnpm-workspace.yaml"
collect workspace-config-change
assert_payload_changed npm-config-change workspace-config-change

# Auto-discovered target shape changes even without editing Cargo.toml.
mkdir -p "$fixture/crates/sample/examples"
printf 'fn main() { println!("source body is not copied"); }\n' \
  > "$fixture/crates/sample/examples/probe.rs"
collect target-change
assert_payload_changed workspace-config-change target-change
[[ "$(cat "$temporary_directory/bundles/target-change/dependencies/crates/sample/examples/probe.rs")" \
  == 'fn main() {}' ]]

expect_failure collect invalid-profile invalid
expect_failure "$BASH" "$collector" --source "$temporary_directory" \
  --output "$temporary_directory/bundles/not-a-checkout" --profile public
expect_failure "$BASH" "$collector" --source "$fixture" --output "$fixture" --profile public
[[ -f "$fixture/Cargo.toml" ]]

# Failed discovery must not be mistaken for an empty, complete inventory.
# Each mock exits successfully except for the one producer under test.
mock_bin="$temporary_directory/mock-bin"
mkdir -p "$mock_bin"
cat > "$mock_bin/cargo" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case "$COLLECTOR_FAILURE_MODE" in
  malformed-metadata)
    printf '{"unexpected":[]}\n'
    ;;
  malformed-targets)
    jq -n --arg source "$PWD" \
      '{packages: [{manifest_path: ($source + "/Cargo.toml"), targets: [{src_path: ($source + "/src/lib.rs"), kind: null}]}]}'
    ;;
  outside-manifest)
    printf '{"packages":[{"manifest_path":"/outside/Cargo.toml","targets":[]}]}\n'
    ;;
  *) exec "$COLLECTOR_REAL_CARGO" "$@" ;;
esac
EOF
cat > "$mock_bin/git" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ "$COLLECTOR_FAILURE_MODE" == failed-list && "${3:-}" == ls-files ]]; then
  printf 'website/package-lock.json\0'
  echo 'simulated tracked-file discovery failure' >&2
  exit 31
fi
exec "$COLLECTOR_REAL_GIT" "$@"
EOF
chmod +x "$mock_bin/cargo" "$mock_bin/git"
for failure_mode in malformed-metadata malformed-targets outside-manifest failed-list; do
  expect_failure env PATH="$mock_bin:$(dirname "$BASH"):$PATH" \
    COLLECTOR_REAL_CARGO="$(command -v cargo)" COLLECTOR_REAL_GIT="$(command -v git)" \
    COLLECTOR_FAILURE_MODE="$failure_mode" \
    "$BASH" "$collector" --source "$fixture" \
    --output "$temporary_directory/bundles/$failure_mode" --profile public
  [[ ! -e "$temporary_directory/bundles/$failure_mode/dependencies/dependency-index.json" ]]
  [[ ! -e "$temporary_directory/bundles/$failure_mode/manifest-index.json" ]]
done

printf 'invalid cargo manifest\n' > "$fixture/Cargo.toml"
expect_failure collect invalid-cargo
[[ ! -e "$temporary_directory/bundles/invalid-cargo/dependencies/dependency-index.json" ]]
[[ ! -e "$temporary_directory/bundles/invalid-cargo/manifest-index.json" ]]

echo "Manifest collection payload and provenance tests passed"
