#!/usr/bin/env bash
set -euo pipefail

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
collector="$repository_root/scripts/collect-manifests.sh"
temporary_directory="$(mktemp -d)"
trap 'rm -rf "$temporary_directory"' EXIT
fixture="$temporary_directory/source"
mkdir -p "$fixture/crates/sample/src" "$fixture/crates/mesh-llm-ui" \
  "$fixture/website" "$temporary_directory/bundles"

expect_failure() {
  if "$@" >"$temporary_directory/failure.log" 2>&1; then
    echo "expected command to fail: $*" >&2
    exit 1
  fi
}

collect() {
  "$BASH" "$collector" --source "$fixture" \
    --output "$temporary_directory/bundles/$1" --profile "${2:-public}"
}

commit_fixture() {
  git -C "$fixture" add .
  git -C "$fixture" -c user.name='Collector fixture' \
    -c user.email=collector@example.invalid -c commit.gpgsign=false \
    -c core.hooksPath=/dev/null commit -qm "$1"
}

hash_file() {
  if command -v sha256sum >/dev/null; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

assert_payload() {
  local directory="$temporary_directory/bundles/$1/dependencies"
  local path expected
  jq -e '.schema == 1 and (keys == ["files", "schema"])
    and (.files | length > 0)
    and all(.files[]; keys == ["path", "sha256"])
    and ([.files[].path] == ([.files[].path] | sort | unique))' \
    "$directory/dependency-index.json" >/dev/null
  while IFS=$'\t' read -r path expected; do
    [[ "$(hash_file "$directory/$path")" == "$expected" ]]
  done < <(jq -r '.files[] | [.path, .sha256] | @tsv' \
    "$directory/dependency-index.json")
  (cd "$directory" && find . -type f ! -name dependency-index.json \
    | sed 's|^./||' | LC_ALL=C sort) > "$temporary_directory/actual-files"
  jq -r '.files[].path' "$directory/dependency-index.json" \
    > "$temporary_directory/index-files"
  cmp "$temporary_directory/actual-files" "$temporary_directory/index-files"
}

assert_payload_changed() {
  local before="$temporary_directory/bundles/$1/dependencies/dependency-index.json"
  local after="$temporary_directory/bundles/$2/dependencies/dependency-index.json"
  if cmp -s "$before" "$after"; then
    echo "dependency change did not change the payload index: $1 -> $2" >&2
    exit 1
  fi
  assert_payload "$2"
}

cat > "$fixture/Cargo.toml" <<'EOF'
[workspace]
members = ["crates/sample"]
resolver = "2"
EOF
cat > "$fixture/Cargo.lock" <<'EOF'
# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "collector-sample"
version = "0.1.0"
EOF
cat > "$fixture/crates/sample/Cargo.toml" <<'EOF'
[package]
name = "collector-sample"
version = "0.1.0"
edition = "2021"
EOF
printf 'pub fn original() {}\n' > "$fixture/crates/sample/src/lib.rs"
printf '{"name":"ui","private":true}\n' > "$fixture/crates/mesh-llm-ui/package.json"
printf 'engine-strict=true\n' > "$fixture/crates/mesh-llm-ui/.npmrc"
printf 'packages:\n  - "."\n' > "$fixture/crates/mesh-llm-ui/pnpm-workspace.yaml"
printf '{"name":"website","lockfileVersion":3,"packages":{}}\n' \
  > "$fixture/website/package-lock.json"
printf 'Initial source documentation\n' > "$fixture/README.md"
git -C "$fixture" init -q
commit_fixture baseline
collect baseline
collect repeat
diff -qr "$temporary_directory/bundles/baseline" "$temporary_directory/bundles/repeat"
assert_payload baseline
baseline="$temporary_directory/bundles/baseline"
[[ "$(cat "$baseline/source-revision.txt")" == "$(git -C "$fixture" rev-parse HEAD)" ]]
[[ "$(cat "$baseline/profile.txt")" == public ]]
[[ ! -e "$baseline/Cargo.toml" && ! -e "$baseline/dependencies/README.md" ]]
jq -e '.profile == "public" and (.source_revision | test("^[0-9a-f]{40}$"))
  and any(.manifests[]; .path == "crates/mesh-llm-ui/.npmrc" and .ecosystem == "configuration")
  and any(.manifests[]; .path == "crates/mesh-llm-ui/pnpm-workspace.yaml" and .ecosystem == "configuration")
  and all(.manifests[]; .path != "crates/sample/src/lib.rs")' \
  "$baseline/manifest-index.json" >/dev/null
[[ "$(cat "$baseline/dependencies/crates/sample/src/lib.rs")" == '#![allow(dead_code)]' ]]

# A new source revision changes audit metadata, not resolution inputs or stubs.
printf 'New source documentation\n' > "$fixture/README.md"
printf 'pub fn changed_source() {}\n' > "$fixture/crates/sample/src/lib.rs"
commit_fixture source-only
collect source-only
diff -qr "$baseline/dependencies" "$temporary_directory/bundles/source-only/dependencies"
expect_failure cmp -s "$baseline/source-revision.txt" \
  "$temporary_directory/bundles/source-only/source-revision.txt"
expect_failure cmp -s "$baseline/manifest-index.json" \
  "$temporary_directory/bundles/source-only/manifest-index.json"

collect self-hosted self-hosted
diff -qr "$temporary_directory/bundles/source-only/dependencies" \
  "$temporary_directory/bundles/self-hosted/dependencies"
jq -e '.profile == "self-hosted"' \
  "$temporary_directory/bundles/self-hosted/manifest-index.json" >/dev/null

# Only tracked package-manager configuration is included.
mkdir -p "$fixture/untracked"
printf 'engine-strict=false\n' > "$fixture/untracked/.npmrc"
collect untracked
diff -qr "$baseline/dependencies" "$temporary_directory/bundles/untracked/dependencies"

printf '{"name":"website","lockfileVersion":3,"packages":{"":{"version":"2.0.0"}}}\n' \
  > "$fixture/website/package-lock.json"
collect dependency-change
assert_payload_changed source-only dependency-change

printf 'engine-strict=false\n' > "$fixture/crates/mesh-llm-ui/.npmrc"
collect npm-config-change
assert_payload_changed dependency-change npm-config-change

printf 'packages:\n  - "."\noverrides:\n  example: 1.0.0\n' \
  > "$fixture/crates/mesh-llm-ui/pnpm-workspace.yaml"
collect workspace-config-change
assert_payload_changed npm-config-change workspace-config-change

# Auto-discovered target shape changes even without editing Cargo.toml.
mkdir -p "$fixture/crates/sample/examples"
printf 'fn main() { println!("source body is not copied"); }\n' \
  > "$fixture/crates/sample/examples/probe.rs"
collect target-change
assert_payload_changed workspace-config-change target-change
[[ "$(cat "$temporary_directory/bundles/target-change/dependencies/crates/sample/examples/probe.rs")" \
  == 'fn main() {}' ]]

expect_failure collect invalid-profile invalid
expect_failure "$BASH" "$collector" --source "$temporary_directory" \
  --output "$temporary_directory/bundles/not-a-checkout" --profile public
expect_failure "$BASH" "$collector" --source "$fixture" --output "$fixture" --profile public
[[ -f "$fixture/Cargo.toml" ]]

# Failed discovery must not be mistaken for an empty, complete inventory.
# Each mock exits successfully except for the one producer under test.
mock_bin="$temporary_directory/mock-bin"
mkdir -p "$mock_bin"
cat > "$mock_bin/cargo" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
case "$COLLECTOR_FAILURE_MODE" in
  malformed-metadata)
    printf '{"unexpected":[]}\n'
    ;;
  malformed-targets)
    jq -n --arg source "$PWD" \
      '{packages: [{manifest_path: ($source + "/Cargo.toml"), targets: [{src_path: ($source + "/src/lib.rs"), kind: null}]}]}'
    ;;
  outside-manifest)
    printf '{"packages":[{"manifest_path":"/outside/Cargo.toml","targets":[]}]}\n'
    ;;
  *) exec "$COLLECTOR_REAL_CARGO" "$@" ;;
esac
EOF
cat > "$mock_bin/git" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if [[ "$COLLECTOR_FAILURE_MODE" == failed-list && "${3:-}" == ls-files ]]; then
  printf 'website/package-lock.json\0'
  echo 'simulated tracked-file discovery failure' >&2
  exit 31
fi
exec "$COLLECTOR_REAL_GIT" "$@"
EOF
chmod +x "$mock_bin/cargo" "$mock_bin/git"
for failure_mode in malformed-metadata malformed-targets outside-manifest failed-list; do
  expect_failure env PATH="$mock_bin:$(dirname "$BASH"):$PATH" \
    COLLECTOR_REAL_CARGO="$(command -v cargo)" COLLECTOR_REAL_GIT="$(command -v git)" \
    COLLECTOR_FAILURE_MODE="$failure_mode" \
    "$BASH" "$collector" --source "$fixture" \
    --output "$temporary_directory/bundles/$failure_mode" --profile public
  [[ ! -e "$temporary_directory/bundles/$failure_mode/dependencies/dependency-index.json" ]]
  [[ ! -e "$temporary_directory/bundles/$failure_mode/manifest-index.json" ]]
done

printf 'invalid cargo manifest\n' > "$fixture/Cargo.toml"
expect_failure collect invalid-cargo
[[ ! -e "$temporary_directory/bundles/invalid-cargo/dependencies/dependency-index.json" ]]
[[ ! -e "$temporary_directory/bundles/invalid-cargo/manifest-index.json" ]]

echo "Manifest collection payload and provenance tests passed"
